# Generated by Django 5.0.3 on 2024-04-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='byte',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='extention',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='byte',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='extention',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
